# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(834, 444)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(670, 370, 111, 51))
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.frame_4 = QtWidgets.QLabel(Dialog)
        self.frame_4.setGeometry(QtCore.QRect(230, 240, 38, 16))
        self.frame_4.setBaseSize(QtCore.QSize(200, 200))
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QLabel(Dialog)
        self.frame_5.setGeometry(QtCore.QRect(490, 240, 38, 16))
        self.frame_5.setBaseSize(QtCore.QSize(200, 200))
        self.frame_5.setObjectName("frame_5")
        self.frame_2 = QtWidgets.QLabel(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(330, 60, 38, 16))
        self.frame_2.setBaseSize(QtCore.QSize(200, 200))
        self.frame_2.setObjectName("frame_2")
        self.frame_1 = QtWidgets.QLabel(Dialog)
        self.frame_1.setGeometry(QtCore.QRect(80, 60, 38, 16))
        self.frame_1.setBaseSize(QtCore.QSize(200, 200))
        self.frame_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frame_1.setObjectName("frame_1")
        self.frame_3 = QtWidgets.QLabel(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(560, 60, 38, 16))
        self.frame_3.setBaseSize(QtCore.QSize(200, 200))
        self.frame_3.setObjectName("frame_3")
        self.Equip_3 = QtWidgets.QLabel(Dialog)
        self.Equip_3.setGeometry(QtCore.QRect(650, 60, 38, 16))
        self.Equip_3.setObjectName("Equip_3")
        self.Equip_1 = QtWidgets.QLabel(Dialog)
        self.Equip_1.setGeometry(QtCore.QRect(180, 60, 38, 16))
        self.Equip_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Equip_1.setObjectName("Equip_1")
        self.Equip_4 = QtWidgets.QLabel(Dialog)
        self.Equip_4.setGeometry(QtCore.QRect(570, 240, 38, 16))
        self.Equip_4.setObjectName("Equip_4")
        self.Equip_5 = QtWidgets.QLabel(Dialog)
        self.Equip_5.setGeometry(QtCore.QRect(310, 240, 38, 16))
        self.Equip_5.setObjectName("Equip_5")
        self.Equip_2 = QtWidgets.QLabel(Dialog)
        self.Equip_2.setGeometry(QtCore.QRect(440, 60, 38, 16))
        self.Equip_2.setObjectName("Equip_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "装备随机生成器"))
        self.pushButton.setText(_translate("Dialog", "随机生成！"))
        self.frame_4.setText(_translate("Dialog", "图4"))
        self.frame_5.setText(_translate("Dialog", "图5"))
        self.frame_2.setText(_translate("Dialog", "图2"))
        self.frame_1.setText(_translate("Dialog", "图1"))
        self.frame_3.setText(_translate("Dialog", "图3"))
        self.Equip_3.setText(_translate("Dialog", "装备3"))
        self.Equip_1.setText(_translate("Dialog", "装备1"))
        self.Equip_4.setText(_translate("Dialog", "装备5"))
        self.Equip_5.setText(_translate("Dialog", "装备4"))
        self.Equip_2.setText(_translate("Dialog", "装备2"))
